<?php

declare(strict_types=1);

namespace PHPTypeS\Bridge\Generators;

use PHPTypeS\Bridge\Generators\Contracts\GeneratorInterface;
use PHPTypeS\Bridge\Generators\Output\GeneratorOutput;
use PHPTypeS\Bridge\Schema\ApiSchema;
use PHPTypeS\Bridge\Schema\EndpointSchema;
use PHPTypeS\Bridge\Schema\Nodes\ArrayTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\RefTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\ScalarTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\TypeNode;
use PHPTypeS\Bridge\Schema\Nodes\UnionTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\EnumTypeNode;

final class FetchClientGenerator implements GeneratorInterface
{
    public function __construct(
        private readonly TypeScriptTypeGenerator $tsGenerator = new TypeScriptTypeGenerator(),
    ) {}

    public function generate(ApiSchema $schema): GeneratorOutput
    {
        $imports   = $this->buildImports($schema);
        $errorClass = $this->buildErrorClass();
        $factory   = $this->buildFactory($schema);

        $content = implode("\n", [
            $this->header(),
            $imports,
            $errorClass,
            $factory,
        ]);

        return new GeneratorOutput(
            filename: 'api.client.ts',
            content: $content,
        );
    }

    private function header(): string
    {
        return <<<'TS'
            /**
             * AUTO-GENERATED by ielfran/phptypes-bridge — DO NOT EDIT MANUALLY.
             * Re-run `vendor/bin/phptypes generate` to update.
             *
             * @see https://github.com/ielfran/phptypes-bridge
             */

            TS;
    }

    private function buildImports(ApiSchema $schema): string
    {
        $typeNames   = [];
        $schemaNames = [];
        $needsZod    = false;

        foreach ($schema->dtos() as $dto) {
            $typeNames[]   = $dto->shortName();
            $schemaNames[] = $dto->shortName() . 'Schema';
        }

        foreach ($schema->enums() as $enum) {
            $typeNames[] = $enum->shortName();
        }

        foreach ($schema->endpoints() as $endpoint) {
            $rt = $endpoint->responseType();
            if ($rt instanceof ArrayTypeNode && $rt->itemType() instanceof RefTypeNode) {
                $needsZod = true;
                break;
            }
        }

        $lines = [];

        if ($needsZod) {
            $lines[] = "import { z } from 'zod';";
        }

        if ($typeNames !== []) {
            $lines[] = "import type { " . implode(', ', $typeNames) . " } from './api.types';";
        }

        if ($schemaNames !== []) {
            $lines[] = "import { " . implode(', ', $schemaNames) . " } from './api.schemas';";
        }

        $lines[] = '';

        return implode("\n", $lines);
    }



    private function buildErrorClass(): string
    {
        return <<<'TS'
            export class ApiError extends Error {
              constructor(
                public readonly status: number,
                public readonly body: string,
              ) {
                super(`API error ${status}: ${body}`);
                this.name = 'ApiError';
              }
            }

            TS;
    }

    private function buildFactory(ApiSchema $schema): string
    {
        $lines = [];

        $lines[] = 'export interface ApiClientOptions {';
        $lines[] = '  /** Default headers merged into every request */';
        $lines[] = '  headers?: Record<string, string>;';
        $lines[] = '  /** Override the global fetch (useful for testing / SSR) */';
        $lines[] = '  fetch?: typeof fetch;';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = 'export function createApiClient(baseUrl: string, options: ApiClientOptions = {}) {';
        $lines[] = '  const _fetch = options.fetch ?? fetch;';
        $lines[] = '  const _headers = options.headers ?? {};';
        $lines[] = '';

        foreach ($schema->endpoints() as $endpoint) {
            foreach ($this->buildEndpointFunction($endpoint, $schema) as $line) {
                $lines[] = '  ' . $line;
            }
            $lines[] = '';
        }

        $lines[] = '  return {';
        foreach ($schema->endpoints() as $endpoint) {
            $lines[] = "    {$endpoint->name()},";
        }
        $lines[] = '  };';
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /** @return list<string> */
    private function buildEndpointFunction(EndpointSchema $endpoint, ApiSchema $schema): array
    {
        $lines = [];

        $params     = $this->buildParams($endpoint, $schema);
        $returnType = $this->buildReturnType($endpoint, $schema);

        $lines[] = "async function {$endpoint->name()}({$params}): Promise<{$returnType}> {";

        $url = $this->buildUrl($endpoint);
        $lines[] = "  const url = {$url};";

        $lines[] = '  const response = await _fetch(url, {';
        $lines[] = "    method: '{$endpoint->httpMethod()}',";
        $lines[] = '    headers: { \'Content-Type\': \'application/json\', ..._headers },';

        if ($endpoint->hasRequestBody()) {
            $lines[] = '    body: JSON.stringify(body),';
        }

        $lines[] = '  });';
        $lines[] = '';

        $lines[] = '  if (!response.ok) {';
        $lines[] = '    throw new ApiError(response.status, await response.text());';
        $lines[] = '  }';
        $lines[] = '';

        if ($endpoint->responseType() === null) {
            $lines[] = '  return;';
        } else {
            $schemaExpr = $this->buildZodParseExpression($endpoint->responseType());

            if ($schemaExpr !== null) {
                $lines[] = "  return {$schemaExpr}.parse(await response.json());";
            } else {
                $lines[] = '  return response.json();';
            }
        }

        $lines[] = '}';

        return $lines;
    }


    private function buildParams(EndpointSchema $endpoint, ApiSchema $schema): string
    {
        $params = [];

        foreach ($endpoint->pathParams() as $param) {
            $type     = $this->inferPathParamType($param);
            $params[] = "{$param}: {$type}";
        }

        if ($endpoint->hasRequestBody() && $endpoint->requestType() !== null) {
            $tsType   = $this->tsGenerator->renderTypeNode($endpoint->requestType(), $schema);
            $params[] = "body: {$tsType}";
        }

        foreach ($endpoint->queryParams() as $qp) {
            $params[] = "{$qp}?: string";
        }

        return implode(', ', $params);
    }

    private function buildReturnType(EndpointSchema $endpoint, ApiSchema $schema): string
    {
        if ($endpoint->responseType() === null) {
            return 'void';
        }

        $type = $endpoint->responseType();

        if ($type instanceof ArrayTypeNode) {
            $itemType = $type->itemType();
            if ($itemType instanceof RefTypeNode) {
                return "{$itemType->shortName()}[]";
            }
        }

        return $this->tsGenerator->renderTypeNode($type, $schema);
    }


    private function buildUrl(EndpointSchema $endpoint): string
    {
        $path = $endpoint->path();

        $interpolated = preg_replace('/\{([^}]+)\}/', '${$1}', $path);

        $hasQueryParams = $endpoint->queryParams() !== [];
        $base = "`\${baseUrl}{$interpolated}`";

        if (!$hasQueryParams) {
            return $base;
        }

        $qpLines = [];
        foreach ($endpoint->queryParams() as $qp) {
            $qpLines[] = "if ({$qp} !== undefined) params.append('{$qp}', {$qp});";
        }

        return $base;
    }


    private function buildZodParseExpression(TypeNode $type): ?string
    {
        if ($type instanceof RefTypeNode) {
            return $type->shortName() . 'Schema';
        }

        if ($type instanceof ArrayTypeNode) {
            $itemType = $type->itemType();
            if ($itemType instanceof RefTypeNode) {
                return "z.array({$itemType->shortName()}Schema)";
            }
        }
        return null;
    }


    private function inferPathParamType(string $paramName): string
    {
        if (in_array($paramName, ['id', 'userId', 'user_id', 'count', 'page', 'limit'], true)) {
            return 'number';
        }

        return 'string';
    }
}
