<?php

declare(strict_types=1);

namespace PHPTypeS\Bridge\Generators;

use PHPTypeS\Bridge\Generators\Contracts\GeneratorInterface;
use PHPTypeS\Bridge\Generators\Output\GeneratorOutput;
use PHPTypeS\Bridge\Schema\ApiSchema;
use PHPTypeS\Bridge\Schema\DtoSchema;
use PHPTypeS\Bridge\Schema\Nodes\ArrayTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\IntersectionTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\EnumTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\RefTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\ScalarTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\TypeNode;
use PHPTypeS\Bridge\Schema\Nodes\UnionTypeNode;
use PHPTypeS\Bridge\Schema\PropertySchema;

final class TypeScriptTypeGenerator implements GeneratorInterface
{
    private const HEADER = <<<'TS'
        /**
         * AUTO-GENERATED by ielfran/phptypes-bridge — DO NOT EDIT MANUALLY.
         * Re-run `vendor/bin/phptypes generate` to update.
         *
         * @see https://github.com/ielfran/phptypes-bridge
         *
         * PHP REQUIREMENT — every DTO class returned from a controller must implement
         * \JsonSerializable and use the JsonSerializableDto trait, otherwise Laravel
         * will throw a 500 TypeError when sending the response.
         *
         * Quick setup:
         *   1. Run `php artisan phptypes:generate` — this auto-generates
         *      app/DTOs/JsonSerializableDto.php
         *   2. Add to each response DTO:
         *
         *        class BookDto implements \JsonSerializable
         *        {
         *            use \App\DTOs\JsonSerializableDto;
         *            public function __construct(...) {}
         *        }
         *
         * Request DTOs (CreateBookRequest etc.) do NOT need this —
         * they are never returned as responses.
         */

        TS;
    
    public function generate(ApiSchema $schema): GeneratorOutput
    {
        $parts = [self::HEADER];

        foreach ($schema->enums() as $enum) {
            $parts[] = $this->renderEnum($enum);
        }

        foreach ($schema->dtos() as $dto) {
            $parts[] = $this->renderInterface($dto, $schema);
        }

        return new GeneratorOutput(
            filename: 'api.types.ts',
            content: implode("\n", $parts),
        );
    }

    private function renderEnum(EnumTypeNode $enum): string
    {
        $name   = $enum->shortName();
        $lines  = [];

        $lines[] = "export const {$name} = {";
        foreach ($enum->cases() as $caseName => $value) {
            $rendered = is_string($value) ? "'{$value}'" : (string) $value;
            $lines[] = "  {$caseName}: {$rendered},";
        }
        $lines[] = '} as const;';
        $lines[] = '';

        $lines[] = "export type {$name} = typeof {$name}[keyof typeof {$name}];";
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function renderInterface(DtoSchema $dto, ApiSchema $schema): string
    {
        $name    = $dto->shortName();
        $generics = $dto->isGeneric()
            ? '<' . implode(', ', $dto->generics()) . '>'
            : '';

        $lines   = [];
        $lines[] = "export interface {$name}{$generics} {";

        foreach ($dto->properties() as $prop) {
            $lines[] = $this->renderProperty($prop, $schema);
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function renderProperty(PropertySchema $prop, ApiSchema $schema): string
    {
        $comment = $prop->docComment() !== null
            ? "  /** {$prop->docComment()} */\n"
            : '';

        $optionalMark = $prop->isOptional() ? '?' : '';
        $tsType       = $this->renderTypeNode($prop->typeNode(), $schema);

        return "{$comment}  {$prop->name()}{$optionalMark}: {$tsType};";
    }

    public function renderTypeNode(TypeNode $node, ApiSchema $schema): string
    {
        $base = match ($node->kind()) {
            ScalarTypeNode::KIND => $this->renderScalar($node),
            ArrayTypeNode::KIND  => $this->renderArray($node, $schema),
            UnionTypeNode::KIND  => $this->renderUnion($node, $schema),
            EnumTypeNode::KIND   => $node->shortName(),
            RefTypeNode::KIND    => $this->renderRef($node, $schema),
            IntersectionTypeNode::KIND => $this->renderIntersection($node, $schema),
            default              => throw new \LogicException(
                "Unhandled TypeNode kind: {$node->kind()}. "
                . 'Add a case to TypeScriptTypeGenerator::renderTypeNode().'
            ),
        };

        if ($node->isNullable()) {
            return "{$base} | null";
        }

        return $base;
    }

    private function renderScalar(ScalarTypeNode $node): string
    {
        return $node->tsType();
    }

    private function renderArray(ArrayTypeNode $node, ApiSchema $schema): string
    {
        $item = $this->renderTypeNode($node->itemType(), $schema);

        if ($node->itemType() instanceof UnionTypeNode
            || $node->itemType()->isNullable()
        ) {
            return "({$item})[]";
        }

        return "{$item}[]";
    }

    private function renderUnion(UnionTypeNode $node, ApiSchema $schema): string
    {
        $parts = array_map(
            fn(TypeNode $t) => $this->renderTypeNode($t, $schema),
            $node->types()
        );

        return implode(' | ', $parts);
    }

    private function renderRef(RefTypeNode $node, ApiSchema $schema): string
    {
        if (!$schema->hasDto($node->fqcn())) {
        }

        return $node->shortName();
    }

    private function renderIntersection(IntersectionTypeNode $node, ApiSchema $schema): string
    {
        $parts = array_map(
            fn(TypeNode $t) => $this->renderTypeNode($t, $schema),
            $node->types()
        );

        return implode(' & ', $parts);
    }
}