<?php

declare(strict_types=1);

namespace PHPTypeS\Bridge\Generators;

use PHPTypeS\Bridge\Generators\Contracts\GeneratorInterface;
use PHPTypeS\Bridge\Generators\Output\GeneratorOutput;
use PHPTypeS\Bridge\Schema\ApiSchema;
use PHPTypeS\Bridge\Schema\DtoSchema;
use PHPTypeS\Bridge\Schema\Nodes\ArrayTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\IntersectionTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\EnumTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\RefTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\ScalarTypeNode;
use PHPTypeS\Bridge\Schema\Nodes\TypeNode;
use PHPTypeS\Bridge\Schema\Nodes\UnionTypeNode;
use PHPTypeS\Bridge\Schema\PropertySchema;

final class ZodSchemaGenerator implements GeneratorInterface
{
    private const HEADER = <<<'TS'
        /**
         * AUTO-GENERATED by PHPTypeS/bridge — DO NOT EDIT MANUALLY.
         * Re-run `vendor/bin/bridge generate` to update.
         *
         * @see https://github.com/PHPTypeS/bridge
         */

        import { z } from 'zod';

        TS;

    public function generate(ApiSchema $schema): GeneratorOutput
    {
        $parts = [self::HEADER];
    
        foreach ($schema->enums() as $enum) {
            $parts[] = $this->renderEnumSchema($enum);
        }
    
        foreach ($this->sortDtos($schema->dtos(), $schema) as $dto) {
            $parts[] = $this->renderDtoSchema($dto, $schema);
        }
    
        return new GeneratorOutput(
            filename: 'api.schemas.ts',
            content: implode("\n", $parts),
        );
    }
    
    private function sortDtos(array $dtos, ApiSchema $schema): array
    {
        $byName = [];
        foreach ($dtos as $dto) {
            $byName[$dto->shortName()] = $dto;
        }
    
        $sorted  = [];
        $visited = [];
    
        $visit = function (DtoSchema $dto) use (&$visit, &$sorted, &$visited, $byName): void {
            $name = $dto->shortName();
    
            if (isset($visited[$name])) {
                return;
            }
    
            $visited[$name] = true;
    
            foreach ($dto->properties() as $prop) {
                $this->collectRefs($prop->typeNode(), function (string $refName) use (&$visit, $byName): void {
                    if (isset($byName[$refName])) {
                        $visit($byName[$refName]);
                    }
                });
            }
    
            $sorted[] = $dto;
        };
    
        foreach ($dtos as $dto) {
            $visit($dto);
        }
    
        return $sorted;
    }
    
    private function collectRefs(TypeNode $node, callable $callback): void
    {
        if ($node instanceof RefTypeNode) {
            $callback($node->shortName());
            return;
        }
    
        if ($node instanceof ArrayTypeNode) {
            $this->collectRefs($node->itemType(), $callback);
            return;
        }
    
        if ($node instanceof UnionTypeNode || $node instanceof IntersectionTypeNode) {
            foreach ($node->types() as $t) {
                $this->collectRefs($t, $callback);
            }
        }
    }

    private function renderEnumSchema(EnumTypeNode $enum): string
    {
        $name   = $enum->shortName();
        $values = array_values($enum->cases());

        $renderedValues = implode(', ', array_map(
            fn($v) => is_string($v) ? "'{$v}'" : (string) $v,
            $values
        ));

        $lines   = [];
        $lines[] = "export const {$name}Schema = z.enum([{$renderedValues}]);";
        $lines[] = "export type {$name} = z.infer<typeof {$name}Schema>;";
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function renderDtoSchema(DtoSchema $dto, ApiSchema $schema): string
    {
        $name    = $dto->shortName();
        $lines   = [];

        $lines[] = "export const {$name}Schema = z.object({";

        foreach ($dto->properties() as $prop) {
            $lines[] = $this->renderPropertySchema($prop, $schema);
        }

        $lines[] = '});';
        $lines[] = "export type {$name} = z.infer<typeof {$name}Schema>;";
        $lines[] = '';

        return implode("\n", $lines);
    }

    private function renderPropertySchema(PropertySchema $prop, ApiSchema $schema): string
    {
        $zodExpr = $this->renderTypeNodeZod($prop->typeNode(), $schema);

        if ($prop->typeNode()->isNullable()) {
            $zodExpr .= '.nullable()';
        }

        if ($prop->isOptional()) {
            $zodExpr .= '.optional()';
        }

        return "  {$prop->name()}: {$zodExpr},";
    }

    public function renderTypeNodeZod(TypeNode $node, ApiSchema $schema): string
    {
        return match ($node->kind()) {
            ScalarTypeNode::KIND => $this->renderScalarZod($node),
            ArrayTypeNode::KIND  => $this->renderArrayZod($node, $schema),
            UnionTypeNode::KIND  => $this->renderUnionZod($node, $schema),
            EnumTypeNode::KIND   => $this->renderEnumZod($node),
            RefTypeNode::KIND    => $this->renderRefZod($node),
            IntersectionTypeNode::KIND => $this->renderIntersectionZod($node, $schema),
            default              => throw new \LogicException(
                "Unhandled TypeNode kind: {$node->kind()}. "
                . 'Add a case to ZodSchemaGenerator::renderTypeNodeZod().'
            ),
        };
    }

    private function renderScalarZod(ScalarTypeNode $node): string
    {
        return match ($node->phpType()) {
            'string', 'class-string' => 'z.string()',
            'int', 'float', 'double' => 'z.number()',
            'bool', 'boolean'        => 'z.boolean()',
            'null'                   => 'z.null()',
            'void', 'never'          => 'z.void()',
            default                  => 'z.unknown()',
        };
    }

    private function renderArrayZod(ArrayTypeNode $node, ApiSchema $schema): string
    {
        $itemZod = $this->renderTypeNodeZod($node->itemType(), $schema);

        if ($node->itemType()->isNullable()) {
            $itemZod .= '.nullable()';
        }

        return "z.array({$itemZod})";
    }

    private function renderUnionZod(UnionTypeNode $node, ApiSchema $schema): string
    {
        if (count($node->types()) === 2) {
            $a = $this->renderTypeNodeZod($node->types()[0], $schema);
            $b = $this->renderTypeNodeZod($node->types()[1], $schema);
            return "z.union([{$a}, {$b}])";
        }

        $members = implode(', ', array_map(
            fn(TypeNode $t) => $this->renderTypeNodeZod($t, $schema),
            $node->types()
        ));

        return "z.union([{$members}])";
    }

    private function renderEnumZod(EnumTypeNode $node): string
    {
        return "{$node->shortName()}Schema";
    }

    private function renderRefZod(RefTypeNode $node): string
    {
        return "{$node->shortName()}Schema";
    }

    private function renderIntersectionZod(IntersectionTypeNode $node, ApiSchema $schema): string
    {
        $schemas = array_map(
            fn(TypeNode $t) => $this->renderTypeNodeZod($t, $schema),
            $node->types()
        );

        if (count($schemas) === 2) {
            return "z.intersection({$schemas[0]}, {$schemas[1]})";
        }

        $base = "z.intersection({$schemas[0]}, {$schemas[1]})";
        foreach (array_slice($schemas, 2) as $schema_item) {
            $base .= ".and({$schema_item})";
        }
        return $base;
    }
}